CREATE TABLE IF NOT EXISTS actions (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  label VARCHAR(256) NOT NULL DEFAULT '',
  "group" VARCHAR(128) NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  source_type VARCHAR(64) NOT NULL DEFAULT 'TYPESCRIPT',
  source_url TEXT NOT NULL DEFAULT '',
  js_url TEXT NOT NULL DEFAULT '',
  etag VARCHAR(64) NOT NULL DEFAULT '',
  async BOOLEAN NOT NULL DEFAULT FALSE,
  timeout INTEGER NOT NULL DEFAULT 60,
  version BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS actions_group_name_uidx
  ON actions ("group", name) WHERE deleted_at IS NULL;
